#Theroetical questios

1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it
enhance Python's capabilities for numerical operations?

In [ ]:
#NumPy is a fundamental library in Python for scientific computing and data analysis, providing efficient and versatile tools for working with numerical arrays and matrices.
#Its core purpose is to introduce high-performance multidimensional arrays and a collection of mathematical functions to operate on these arrays.

2. Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the
other?

In [ ]:
#the main diffrence is that np.average()  it can calculate the weihted average.

#other wise you can use np.mean() for faster calculation.

3. Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D
arrays.

In [ ]:
#NumPy provides methods to reverse arrays along specific axes.
#This can be useful for various operations, such as reversing the order of elements in a sequence or reversing the direction of a matrix.

#1D array:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
reversed_arr = arr[::-1]

print(reversed_arr)



#2D array:
arr1=np.array([[1,2,3],
               [4,5,6]])
reversed_arr1=arr1[::-1]
print(reversed_arr1)







[5 4 3 2 1]
[[4 5 6]
 [1 2 3]]


4. How can you determine the data type of elements in a NumPy array? Discuss the importance of data types
in memory management and performance.

In [ ]:
#arr.dtype  The most direct way is to access the dtype attribute of the array:

#Data types are important for memory management because they determine the amount of memory allocated to each element.

#For example, int8 uses 1 byte of memory while int64 uses 8 bytes.

#Using the correct data type can reduce memory usage and improve performance, especially when dealing with large datasets.



arr = np.array([1, 2, 3], dtype=np.int8)
print(arr.dtype)

arr = np.array([1, 2, 3], dtype=np.int64)
print(arr.dtype)

int8
int64


5. Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

In [1]:
#n-dimensional arrays) are the fundamental data structure in NumPy.
#They are homogeneous collections of elements of the same data type, organized in a multidimensional grid.
#This grid is defined by a tuple of integers called the shape of the array, which specifies the size of the array along each dimension.

6. Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

In [2]:

# pre-compiled code for numerical operations.
# NumPy arrays offer substantial performance advantages over Python lists for large-scale numerical operations.
#The contiguous memory allocation, vectorized operations, data type optimization, and hardware optimization of NumPy arrays contribute to significant speed improvements, especially when dealing with large datasets and complex computations.

7. Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and
output.

In [5]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Stack vertically

# vertical Stacks. arrays creating a new array with the same number of columns
#as the input arrays and a total number of rows equal to the sum of the rows in the input arrays.
stack1 = np.vstack((a, b))

# Stack horizontally

# horizontal stack.  creating a new array with the same number of rows as the input arrays and a total number of columns equal to the sum of the columns in the input arrays.
stack2 = np.hstack((a, b))

print(stack1)
print(stack2)


[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


8. Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various
array dimensions.

In [6]:
#fliplr()
#Reverses the order of elements along the last axis (columns).

#effect1D array: Reverses the order of elements.
#effect2D array: Reverses the order of columns.
#effect3D array: Reverses the order of columns in each 2D slice along the first two axes.
#effect Higher dimensions: Reverses the order of elements along the last axis.

#flipud()
#Reverses the order of elements along the first axis (rows).
#Effect on different dimensions:
#1D array: Reverses the order of elements.
#2D array: Reverses the order of rows.
#3D array: Reverses the order of rows in each 2D slice along the last two axes.
#Higher dimensions: Reverses the order of elements along the first axis.

9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

In [7]:
#array_split() function allows uneven splits and handles any remaining elements.
#While split() divides the array into equal-sized sub-arrays, array_split() can handle uneven splits


#Handling Uneven Splits

#If the array cannot be split evenly, array_split() makes the best effort to create sub-arrays of roughly equal size.
#any "leftover" elements are added to the last sub-array.
#This behavior is different from split(), which raises an error if an even split is not possible.

10. Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array
operations?

In [8]:
#vectorization
# Performing operations on entire arrays instead of individual elements using loops.

# Vectorized code is often more readable and compact.


#broadcasting
# Applying operations between arrays with different shapes, subject to certain rules.
#NumPy automatically expands the dimensions of smaller arrays to match larger ones, enabling element-wise operations.
# Broadcasting allows NumPy to automatically adjust the shape of arrays to make element-wise operations compatible, even if the arrays have different shapes.



#Practical Questions:

1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [11]:
ar=np.random.randint(1,200 , (3,3))
print(f"before interchange:{ar}")
interchanged_ar=ar.T
print(f"after interchange: {interchanged_ar}")

before interchange:[[159 189 154]
 [141 166  36]
 [133  18  42]]
after interchange: [[159 141 133]
 [189 166  18]
 [154  36  42]]


2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [15]:
#1d Array

arr= np.arange(10)
print(f"1D array: {arr}")

#reshape in to 2*5
arr1=arr.reshape(2,5)
print(f"2*5 array: {arr1}")

#reshape in to 5*2
arr2=arr1.reshape(5,2)
print(f"5*2 array: {arr2}")

1D array: [0 1 2 3 4 5 6 7 8 9]
2*5 array: [[0 1 2 3 4]
 [5 6 7 8 9]]
5*2 array: [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array

In [19]:
arr=np.random.rand(4,4)
print(f"random floating values:{arr}")

arr1 = np.pad(arr, pad_width=1, mode='constant', constant_values=0)

print(f"after adding the border of 0 :{arr1}")

random floating values:[[0.58509604 0.8809825  0.01784671 0.89655584]
 [0.42655492 0.4432797  0.17951812 0.5390446 ]
 [0.41521051 0.68327766 0.07342208 0.36768532]
 [0.86062998 0.32507304 0.84590977 0.38111224]]
after adding the border of 0 :[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.58509604 0.8809825  0.01784671 0.89655584 0.        ]
 [0.         0.42655492 0.4432797  0.17951812 0.5390446  0.        ]
 [0.         0.41521051 0.68327766 0.07342208 0.36768532 0.        ]
 [0.         0.86062998 0.32507304 0.84590977 0.38111224 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [22]:
arr=np.arange(10,61,5)
print(arr)

[10 15 20 25 30 35 40 45 50 55 60]


5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
(uppercase, lowercase, title case, etc.) to each element.

In [23]:
arr=np.array(['python', 'numpy', 'pandas'])
print(f"original array: {arr}")

upr=np.char.upper(arr)
print(f"uppercase: {upr}")

lower=np.char.lower(arr)
print(f"lowercase: {lower}")

title=np.char.title(arr)
print(f"title case: {title}")

original array: ['python' 'numpy' 'pandas']
uppercase: ['PYTHON' 'NUMPY' 'PANDAS']
lowercase: ['python' 'numpy' 'pandas']
title case: ['Python' 'Numpy' 'Pandas']


6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [24]:



ar= np.array(['hey', 'my', 'self','Anant'])


# Inserting space between each char
np.char.join(' ', ar)



array(['h e y', 'm y', 's e l f', 'A n a n t'], dtype='<U9')

7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [25]:
arr1=np.array([[2,3],[4,6]])
arr2=np.array([[7,9],[10,12]])

print(f"addition: {arr1+arr2}")#addition
print(f"subtraction: {arr1-arr2}")#subtraction
print(f"multiplication: {arr1*arr2}")#multiplication
print(f"division: {arr1/arr2}")#division


addition: [[ 9 12]
 [14 18]]
subtraction: [[-5 -6]
 [-6 -6]]
multiplication: [[14 27]
 [40 72]]
division: [[0.28571429 0.33333333]
 [0.4        0.5       ]]


8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [30]:

matrix = np.identity(5)
print(matrix)
# Extract diagonal elements using diag()
diag = np.diag(identity_matrix)
print(f"digonal{diag}")



[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
digonal[1. 1. 1. 1. 1.]


9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in
this array.

In [38]:
import numpy as np

def is_prime(n):
  if n <= 1:
    return False
  for i in range(2, int(n**0.5) + 1):
    if n % i == 0:
      return False
  return True


arr = np.random.randint(0, 1001, size=100)#array  of 100 radom int between 0 , 1000


prime_numbers = arr[np.vectorize(is_prime)(arr)]
print(f"prime numbers:{prime_numbers}")


prime numbers:[599  11 587 101 599 439  41 881 257 709 977 641]


10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly
averages.

In [58]:


# Assuming 28 days in the month
daily_temp = np.random.randint(35, 43, size=28)


# Reshape into weeks
weekly_temp = daily_temp.reshape(-1, 7)
print(f"weekly temp:{weekly_temp}")
# Calculate weekly averages
weekly_averages = np.mean(weekly_temperatures, axis=1)
print(f"weekly_avg:{weekly_averages}")



weekly temp:[[41 41 36 36 36 39 40]
 [38 40 36 37 35 38 37]
 [40 41 37 41 40 35 37]
 [40 42 35 37 37 39 36]]
weekly_avg:[27.71428571 28.14285714 25.14285714 27.71428571]
